config/routes.rb
Rails.application.routes.draw do
  resources :instruments
  devise_for :users , controllers:{
      registrations: 'registrations'

  }

  root 'instruments#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  mount_uploader :image , ImageUploader
  serialize :image , JSON # if you use SQLite , add this line
  belongs_to :user , optional: true

  validates :title , :brand , :price , :model , presence: true
  validates :description , length: {maximum: 1000 , too_long: "%{count} characteres is  the maximum aloud."}
  validates :title , length: {maximum: 140 , too_long: "%{count} characteres is  the maximum aloud."}
  validates :price , numericality: {only_integer: true } , length: {maximum: 7}

  BRAND = %w{ Fiat Volkswagen Honda Citroen Ford Bmw Ferrari Audi Lifan Hyunday Chevrolet Mini AlfaRomeo }
  FINISH = %w{ Black White Navy Blue Red Clear Satin Yellow Seafoam }
  CONDITION = %w{ New Excellent Mint Used Fair Poor }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :instruments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , except: [:index , :show]

  # GET /instruments
  # GET /instruments.json
  def index
    @instruments = Instrument.all.order("created_at desc")
  end

  # GET /instruments/1
  # GET /instruments/1.json
  def show
  end

  # GET /instruments/new
  def new
    @instrument = current_user.instruments.build
  end

  # GET /instruments/1/edit
  def edit
  end

  # POST /instruments
  # POST /instruments.json
  def create
    @instrument = current_user.instruments.build(instrument_params)

    respond_to do |format|
      if @instrument.save
        format.html { redirect_to @instrument, notice: 'Instrument was successfully created.' }
        format.json { render :show, status: :created, location: @instrument }
      else
        format.html { render :new }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instruments/1
  # PATCH/PUT /instruments/1.json
  def update
    respond_to do |format|
      if @instrument.update(instrument_params)
        format.html { redirect_to @instrument, notice: 'Instrument was successfully updated.' }
        format.json { render :show, status: :ok, location: @instrument }
      else
        format.html { render :edit }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instruments/1
  # DELETE /instruments/1.json
  def destroy
    @instrument.destroy
    respond_to do |format|
      format.html { redirect_to instruments_url, notice: 'Instrument was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instrument
      @instrument = Instrument.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instrument_params
      params.require(:instrument).permit(:brand, :model, :description, :condition, :finish, :title, :price , :image)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


  private

  def sign_up_params

    params.require(:user).permit(:name , :email , :password , :password_confirmation)

  end

  def account_update_params

    params.require(:user).permit(:name , :email , :password , :password_confirmation , :current_password)
  end


end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper

  def instrument_author(instrument)
    user_signed_in? && current_user.id == instrument.user_id
  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/instruments/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for @instrument, html: { multipart: true } do |f| %>
      <%= f.error_notification %>

      <div class="columns">
        <div class="field column is-9">
          <div class="control">
            <%= f.input :title , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="field column">
          <div class="control">
            <%= f.input :price, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

      </div>

      <div class="field">
        <div class="control">
          <%= f.input :model, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
        </div>
      </div>

      <div class="columns">
        <div class="field column is-4">
          <div class="control">
            <label class="label">Brand</label>
            <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :brand, collection: Instrument::BRAND, prompt: "Select brand" %>
                </span>
              <span class="icon is-small is-left">
                  <i class="fa fa-tag"></i>
                </span>
            </div>
          </div>
        </div>

        <div class="field column is-4">
          <div class="control">
            <label class="label">Finish</label>
            <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :finish, collection: Instrument::FINISH, prompt: "Select finish" %>
                </span>
              <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
            </div>
          </div>
        </div>

        <div class="field column is-4">
          <div class="control">
            <label class="label">Condition</label>
            <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :condition, collection: Instrument::CONDITION, prompt: "Select condition" %>
                </span>
              <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
            </div>
          </div>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <label class="label">Add images</label>
          <div class="file">
            <label class="file-label">
              <%= f.input :image, as: :file, input_html: { class:"file-input instrument-image" }, label: false, wrapper: false %>
              <span class="file-cta">
                    <span class="file-icon"><i class="fa fa-upload"></i></span>
                    <span class="file-label">Choose a file…</span>
                  </span>
            </label>
          </div>
        </div>
      </div>
      <output id="list"></output>
      <hr />

      <div class="field is-grouped">
        <div class="control">
          <%= f.button :submit, value:'Criar um novo Carro' , class: 'button is-warning' %>
          <%= link_to 'Cancel', instruments_path, class:'button is-light' %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/instruments/edit.html.erb
<% content_for :header do %>
  <section class="hero is-warning">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">
          Editar Carro
        </h1>
      </div>
    </div>
  </section>
<% end %>

<div class="pv4">
  <%= render 'form', instrument: @instrument %>
</div>

app/views/instruments/index.html.erb
<% content_for :header do %>

  <section class="hero is-warning">

    <div class="hero-body">
      <div class="container">
        <h1 class="title">
          Procure os ultimos carros no Flanger
        </h1>
      </div>
    </div>
  </section>

<% end %>

<div class="instrument-index-grid pt4">
  <% @instruments.each do |instrument|%>

    <div class="instruments border-light">
      <div class="instrument-thumb">
      <%= link_to image_tag(instrument.image_url(:thumb)), instrument %>
      <% if instrument.condition?%>
      <div class="condition">
        <span class="tag is-dark"><%= instrument.condition %></span>
      </div>
        <% end %>
      </div>


    <div class="pa3">
      <h3 class="fw7 f4 title"><%= link_to instrument.title , instrument %></h3>

      <p class="has-text-gray fg pt1">Vendedor:<%= instrument.user.name%></p>

      <p class="f3 fw6 has-text-right pt2 price">R<%= number_to_currency(instrument.price) %></p>

      <% if instrument_author(instrument) %>
        <%= link_to 'Edit', edit_instrument_path(instrument) , class: "button is-small" %>
        <%= link_to 'Delete', instrument , method: :delete, data: { confirm: "Voce tem certeza?"}, class: "button is-small" %>

        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/instruments/new.html.erb
<% content_for :header do %>
  <section class="hero is-warning">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">
          Venda seu carro usado
        </h1>
      </div>
    </div>
  </section>
<% end %>

<div class="pv4">
  <%= render 'form', instrument: @instrument %>
</div>

app/views/instruments/show.html.erb
<% content_for :body_class , 'bg-light' %>

<div class="section instrument-show">
  <div class="columns">
    <div class="column is-8">
      <h1><%= @instrument.title %></h1>

      <ul class="pv1">
        <% if @instrument.brand? %>
         <li class="inline-block pr3"><%= @instrument.brand %></li>
          <% end %>
        <% if @instrument.model? %>
          <li class="inline-block pr3"><%= @instrument.model %></li>
        <% end %>
        <% if @instrument.condition? %>
          <li class="inline-block pr3"><%= @instrument.condition %></li>
        <% end %>
      </ul>
    </div>
    <div class="column is-3 is-offset-1"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flanger</title>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application' %>
</head>

<body class="<%= yield (:body_class) %>">
<% if flash[:notice] %>
  <div class="notification is-success global-notification">
    <p class="notice"><%= notice %></p>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="notification is-danger global-notification">
    <p class="alert"><%= alert %></p>
  </div>
<% end %>
<nav class="navbar is-warning" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class:"navbar-item" do %>
      <h1 class="title is-5">Flanger</h1>
    <% end  %>
    <div class="navbar-burger burger" data-target="navbar">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbar" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="field is-grouped">

          <%# if cart_has_items %>
            <%#= link_to cart_path(@cart), class:"navbar-item button is-warning" do %>
<!--              <span class="icon is-small">-->
<!--                <i class="fa fa-shopping-cart"></i>-->
<!--              </span>-->
<!--              <span>Cart-->
                <%#= cart_count_over_one %>
<!--                </span>-->
            <%# end %>
          <%# end %>

          <% if user_signed_in? %>
            <%= link_to 'Sell', '#', class: "navbar-item button is-dark" %>

            <div class="navbar-item has-dropdown is-hoverable">
              <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
              <div class="navbar-dropdown is-right">
                <%= link_to current_user.name , edit_user_registration_path, class:"navbar-item" %>
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
              </div>
            </div>
          <% else %>

            <%= link_to "Sign In", new_user_session_path, class:"navbar-item button is-warning" %>
            <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button is-warning"%>

          <% end %>

        </div>
      </div>
    </div>
  </div>
</nav>

<%= yield(:header) %>

<div class="container">

  <%= yield %>

</div>

</body>
</html>

app/views/store/index.html.erb
<h1>Store#index</h1>
<p>Find me in app/views/store/index.html.erb</p>